### ISSUE TITLE
Limited Parameters with BlazorTurnstile

### ISSUE THREAD

**Issue by MisterJEFFREY** [MichelJansson/BlazorTurnstile#2]
Greetings.

I've been looking into BlazorTurnstile and find it quite helpful to get started! Thanks for creating this!

However, I've noticed that if I want to customize the widget further, I do not have a way to do so because it does not expose the other parameters, ie: Appearance, id, etc.

Are there any plans to add more parameters to this?

Thanks in advance!

(Edit: Happy thanksgiving!)

**Comment by MichelJansson** [comment]
@MisterJEFFREY, I see no reason not to add support for the different appearance and execution modes - it was just not in scope when I initially created this. I don't have a time frame for it though, so feel free to submit a PR if you're in a hurry!

**Comment by MisterJEFFREY** [comment]
@MichelJansson .
Thanks for the update!

I've added a PR request for you here to add the Appearance parameter for now:
[ https://github.com/MichelJansson/BlazorTurnstile/pull/3 ](https://github.com/MichelJansson/BlazorTurnstile/pull/3)

Please let me know what more I can do for you!

**Comment by MichelJansson** [comment]
Appearance and Execution modes are now both supported and available from [BlazorTurnstile 2.1.0](https://github.com/MichelJansson/BlazorTurnstile/releases/tag/v2.1.0)
